---

- name: Variable expectations are validated
  assert:
      that:
          - 'ipaserver_hostname | default("",True) | trim | length'
          - 'ipaserver_domain | default("",True) | trim | length'
          - 'ipaserver_realm | default("",True) | trim | length'
          - 'ipaserver_admin_principal | default("",True) | trim | length'
          - 'ipaserver_admin_password | default("",True) | trim | length'

- name: The new user e-mail domain and shell are set
  ipa_config:
    ipadefaultemaildomain: '{{ ipaserver_domain.split(".")[-2] }}.{{ ipaserver_domain.split(".") }}'
    ipadefaultloginshell: '/bin/bash'
  environment:
    IPA_HOST: '{{ ipaserver_hostname }}'
    IPA_USER: '{{ ipaserver_admin_principal }}'
    IPA_PASS: '{{ ipaserver_admin_password }}'

- name: Non-client DNS managed entries exist
  ipa_dnsrecord:
    record_name: '{{ item.name | mandatory }}'
    record_ttl: '{{ item.ttl if "ttl" in item else "300" }}'
    record_type: '{{ item.type if "type" in item else omit }}'
    record_value: '{{ item.value | mandatory }}'
    state: '{{ item.state if "state" in item else omit }}'
    zone_name: '{{ item.zone | mandatory }}'
  environment:
    IPA_HOST: '{{ ipaserver_hostname }}'
    IPA_USER: '{{ ipaserver_admin_principal }}'
    IPA_PASS: '{{ ipaserver_admin_password }}'
  with_items: '{{ ipaserver_dnsrecords }}'
