---

- name: The ssh daemon does not allow root logins with a password
  lineinfile:
      path: '/etc/ssh/sshd_config'
      line: '# PermitRootLogin yes  ## MANAGED BY ANSIBLE'
      backrefs: True
      regexp: '^PermitRootLogin yes'
  notify:
      - "restart ssh daemon"

- name: The ssh daemon does not forward X11
  lineinfile:
      path: '/etc/ssh/sshd_config'
      line: '# X11Forwarding yes  ## MANAGED BY ANSIBLE'
      backrefs: True
      regexp: '^X11Forwarding yes'
  notify:
      - "restart ssh daemon"

- name: The ssh daemon only allows public-key root logins
  blockinfile:
      backup: True
      path: '/etc/ssh/sshd_config'
      block: 'PermitRootLogin without-password'
  notify:
      - "restart ssh daemon"
