---

- name: Local copy of certificate and key exist
  assert:
      that:
          - 'letsencrypt_cert_filepath is file'
          - 'letsencrypt_key_filepath is file'

- name: The ca-certificates package is always the latest version
  package:
      name: ca-certificates
      state: latest
  notify: Refresh Trusted CAs

- name: Let's Encrypt intermediate and related root certificates are downloaded
  command: 'curl -LO "{{ item }}"'
  args:
      chdir: '/etc/pki/ca-trust/source/anchors/'
      creates: '/etc/pki/ca-trust/source/anchors/{{ item | basename }}'
  notify: Refresh Trusted CAs
  with_items: '{{ letsencrypt_chain_urls }}'

- name: Deploy Let's Encrypt certificate file
  copy:
      src: '{{ letsencrypt_cert_filepath }}'
      dest: '{{ letsencrypt_dest_cert_filepath }}'
      mode: '0644'
      owner: 'root'
      group: 'root'
  notify: Refresh Trusted CAs

- name: A group named letsencrypt exists
  group:
    name: letsencrypt
    system: True

- name: Deploy Let's Encrypt private key
  copy:
      src: '{{ letsencrypt_key_filepath }}'
      dest: '{{ letsencrypt_dest_key_filepath }}'
      mode: '0640'
      owner: 'root'
      group: 'letsencrypt'
