---

- name: The chrony package is installed
  package:
      name: chrony
      state: present
  register: _tmp_result
  until: _tmp_result is success

- name: The stratum 2 Fedora pool is used as a time source
  blockinfile:
      backup: True
      path: '/etc/chrony.conf'
      block: 'pool 2.fedora.pool.ntp.org iburst'
  notify:
      - "restart chrony daemon"

- name: The chrony daemon is enabled and started
  systemd:
      name: chronyd
      enabled: true
      state: started
