---

all:
    hosts:
        ipa1:
            ansible_host: '{{ _vault_site_ipa1_ip }}'
        ipa2:
            ansible_host: '{{ _vault_site_ipa2_ip }}'
        vmhost1:
            ansible_host: '{{ _vault_site_vmhost1_ip }}'
        smtp1:
            ansible_host: '{{ _vault_site_smtp1_ip }}'
        dhcp1:
            ansible_host: '{{ _vault_site_dhcp1_ip }}'
        dhcp2:
            ansible_host: '{{ _vault_site_dhcp2_ip }}'
        gateway1:
            ansible_host: '{{ _vault_site_gateway1_ip }}'
    vars:
        ansible_connection: 'ssh'
        ansible_user: '{{ _vault_admin_username }}'
        ansible_ssh_pass: '{{ _vault_admin_userpass }}'
        ansible_become_pass: '{{ _vault_admin_userpass }}'
        system_hostname: '{{ _vault_system_hostname }}'
    children:
        gateways:
            hosts:
                gateway1: {}
        ipaservers:
            hosts:
                ipa1: {}
        ipareplicas:
            hosts:
                ipa2: {}
            vars:
                ipaserver_is_replica: True
        ipaconfig:
            hosts:
                ipa1: {}
                ipa2: {}
        ipaclients:
            hosts:
                vmhost1: {}
                dhcp1: {}
                dhcp2: {}
                smtp1: {}
                gateway1: {}
        timeclients:
            hosts:
                ipa1: {}
                ipa2: {}
                vmhost1: {}
                dhcp1: {}
                dhcp2: {}
                smtp1: {}
                gateway1: {}
        qemuvms:
            hosts:
                ipa2: {}
                dhcp1: {}
                smtp1: {}
        qemuhosts:
            hosts:
                vmhost1: {}
        dhcpservers:
            hosts:
                dhcp1: {}
                dhcp2: {}
        smtpservers:
            hosts:
                smtp1: {}
