---

ipaserver_setup_dns: False

ipaserver_packages: >-
    {{ _ipaserver_packages | union(["ipa-server-dns"])
       if ipaserver_setup_dns
       else _ipaserver_packages }}

ipa_install_template: >-
    {{ role_path }}/templates/{{ "ipa_replica_install_command.j2"
                                  if ipaserver_is_replica
                                  else "ipa_server_install_command.j2" }}

ipaserver_marker_fact_filepath: /etc/ansible/facts.d/ipaserver_installed.fact

_ipaserver_dirsrv_pin: >-
    {{ ipaserver_dirsrv_pin | trim
    if ipaserver_dirsrv_pin | default("", True) | trim | length
    else "" }}
_ipaserver_http_pin: >-
    {{ ipaserver_http_pin | trim
       if ipaserver_http_pin  | default("", True) | trim | length
       else "" }}
_ipaserver_pkinit_pin: >-
    {{ ipaserver_pkinit_pin | trim
       if ipaserver_pkinit_pin | default("", True) | trim | length
        else "" }}

# Required for use of older python/firewalld bindings
ansible_python_interpreter: 'python3'

_prefix: '{{ "free" if ansible_distribution == "Fedora" else "" }}'

_ipaserver_packages:
  - '{{ _prefix }}ipa-server'
  - 'bind'
  - 'bind-dyndb-ldap'
  - 'ipa-python'
  - 'sssd-ldap'
  - 'expect'

ipaserver_firewalld_services:
    - 'dns'
    - 'http'
    - 'https'
    - 'kadmin'
    - 'kerberos'
    - 'kpasswd'
    - 'ldap'
    - 'ldaps'
    - 'ntp'
    - '{{_prefix}}ipa-ldap'
    - '{{_prefix}}ipa-ldaps'
    - '{{_prefix}}ipa-replication'
    - '{{_prefix}}ipa-trust'
