---

# IPA Hostname, domain and Keberos Realm
ipaserver_hostname: "{{ ansible_fqdn }}"
ipaserver_domain: "{{ ansible_domain }}"
ipaserver_realm: "{{ ansible_domain | upper }}"
ipaserver_admin_principal: "admin@{{ ipaserver_realm }}"
ipaserver_admin_password: "Secret123"

# List of dictionaries containing keys for ipa_dnsrecord parameters:
# name*, ttl, type, value*, state, zone*
# (* == mandatory)
ipaserver_dnsrecords: []

# List of dictionaries containing keys for ipa_user parameters:
# uid*, uidnumber, gid, ...
# (* == mandatory)
ipaserver_users: []
