---

# IPA Hostname, domain and Keberos Realm
ipaserver_hostname: "{{ ansible_fqdn }}"
ipaserver_domain: "{{ ansible_domain }}"
ipaserver_realm: "{{ ansible_domain | upper }}"
ipaserver_admin_principal: "admin@{{ ipaserver_realm }}"
ipaserver_admin_password: "Secret123"

# List of dictionaries containing keys for ipa_dnsrecord parameters:
# name*, ttl, type, value*, state, zone*
# (* == mandatory)
# Ref: https://docs.ansible.com/ansible/latest/modules/ipa_dnsrecord_module.html#ipa-dnsrecord-module
ipaserver_dnsrecords: []

# List of dictionaries containing keys for ipa_group parameters:
# cn*, gidnumber, group, user, ...
# Ref: https://docs.ansible.com/ansible/latest/modules/ipa_group_module.html#ipa-group-module
ipaserver_groups: []

# List of dictionaries containing keys for ipa_user parameters:
# uid*, uidnumber, gid, ...
# Ref: https://docs.ansible.com/ansible/latest/modules/ipa_user_module.html#ipa-user-module
ipaserver_users: []

# When non-empty, file will be written to /usr/local/sbin/ipaconfig_script.sh
# then executed on one ipaserver host only.  It is assumed the script is idempotent.
# and exits non-zero on failure.  An admin ticket will have already been obtained.
ipaconfig_lib_filepath: '{{ role_path }}/files/ipaconfig_lib.sh'
ipaconfig_script_filepath: '{{ role_path }}/files/ipaconfig_script.sh'
ipaconfig_script_debug: False  # when true, DEBUG=true will be set
