---

# List of dictionaries containing keys for ipa_dnsrecord parameters:
# name*, ttl, type, value*, state, zone*
# (* == mandatory)
ipaserver_dnsrecords: '{{ _vault_ipaserver_dnsrecords }}'
ipaserver_groups: '{{ _vault_ipaserver_groups }}'
ipaserver_users: '{{ _vault_ipaserver_users }}'
ipaserver_commands: '{{ _vault_ipaserver_commands }}'
ipaconfig_script_filepath: '{{ playbook_dir }}/files/ipaconfig_script.sh'
