---

- name: Essential host packages are installed
  package:
      name:
        - ksmtuned
        - libvirt-client
      state: present
  register: _tmp_result
  until: _tmp_result is success

- name: The KSM service is enabled and running
  systemd:
      name: ksm
      enabled: True
      state: '{{ "restarted" when _tmp_result is changed else "started" }}'

- name: The libvirt-guest configuration is set
  lineinfile:
      backup: True
      path: '/etc/sysconfig/libvirt-guest'
      line: '{{ item }}'
  register: _lvg_tmp
  with_items:
      - 'ON_BOOT=start'
      - 'ON_SHUTDOWN=suspend'
      - 'SYNC_TIME=1'  # doesn't work with windows guests

- name: The libvirt-guest service is enabled and running
  systemd:
      name: libvirt-guests
      enabled: True
      state: '{{ "restarted" when _lvg_tmp is changed else "started" }}'
