---

- hosts: 'all'
  gather_facts: True
  pre_tasks:

    - name: 'Validate initial expectations'
      assert:
        that:
            - 'env_name | default("", True) | trim | length'
            - 'terraform_backend | default("", True) | trim | length'
            - 'terraform_provider | default("", True) | trim | length'
            - 'terraform_uuid | default("", True) | trim | length'
            - 'terraform_project | default("", True) | trim | length'

    - name: 'The shared terraform state bucket exists'
      when: "inventory_hostname_short == 'localhost'"
      gcp_storage_bucket:
        auth_kind: 'serviceaccount'
        location: '{{ terraform_backend.region }}'
        name: '{{ terraform_backend.bucket }}'
        project: '{{ terraform_backend.project }}'
        service_account_file: '{{ terraform_backend.credentials }}'
        storage_class: 'REGIONAL'

  tasks:

    - name: 'Terraform project is applied'
      make:
        chdir: "{{ terraform_project }}"
        params: "ENV_NAME={{ env_name }}"
