---

- hosts: 'all'
  gather_facts: True
  pre_tasks:

    - name: 'Validate initial expectations'
      assert:
        that:
            - 'env_name | default("", True) | trim | length'
            - 'terraform.region | default("", True) | trim | length'
            - 'terraform.bucket | default("", True) | trim | length'
            - 'terraform.project | default("", True) | trim | length'
            - 'terraform.credentials | default("", True) | trim | length'
            - 'terraform.env_uuid is search(env_name)'

    - name: 'The shared terraform state bucket exists'
      when: "inventory_hostname_short == 'localhost'"
      gcp_storage_bucket:
        auth_kind: 'serviceaccount'
        location: '{{ terraform.region }}'
        name: '{{ terraform.bucket }}'
        project: '{{ terraform.project }}'
        service_account_file: '{{ terraform.credentials }}'
        storage_class: 'REGIONAL'
