---

- hosts: all
  gather_facts: false
  vars:
      env_name: '{{ inventory_dir | basename}}'
      env_file_dirpath: '{{ playbook_dir }}/{{ env_name }}_files'
  pre_tasks:
      - debug:
          msg: "***** {{ inventory_hostname }} operating in {{ env_name }} environment *****"
  roles:
      - role: ansible_dependencies
      - role: hostname
      - role: basic_lockdown

      - role: slimserver
        when: "'gateways' in group_names"
      - role: gateway
        when: "'gateways' in group_names"

      - role: qemuhost
        when: "'qemuhosts' in group_names"
      - role: qemuvm
        when: "'qemuvms' in group_names"

      - role: timeclient
        when: "'timeclients' in group_names"

      # Register master server first, before any replicas
      - role: ipaserver
        when: "'ipaservers' in group_names"
      - role: ipaserver
        when: "'ipareplicas' in group_names"

      # configuration is replicated, only update one server
      - role: ipaconfig
        when: inventory_hostname == groups['ipareplicas'][-1]

      - role: ipaclient
        when: "'ipaclients' in group_names and
               ( 'ipaservers' not in group_names or
                 'ipareplicas' not in group_names )"

      - role: dhcpserver
        when: "'dhcpservers' in group_names"

      - role: letsencrypt
        when: "'smtpservers' in group_names or 'imapservers' in group_names"

      - role: imapserver
        when: "'imapservers' in group_names"

      - role: saslauth
        when: "'smtpservers' in group_names"

      - role: smtpserver
        when: "'smtpservers' in group_names or 'imapservers' in group_names"

      - role: emailclient
        when: "'smtpservers' not in group_names and 'imapservers' not in group_names"

      - role: therm_email
        when: "'gateways' in group_names"
