---

ipaserver_admin_password: '{{ _vault_ipa_admin_userpass }}'
ipaserver_dir_admin_password: '{{ _vault_ipa_admin_userpass if inventory_hostname == "ipa1" else omit }}'
ipaserver_setup_ntp: False  # use dedicated role
ipaserver_forward_policy: "only"
ipaserver_auto_forwarders: False  # use root servers
