---

- name: Postconf to YAML conversion script is deployed
  copy:
      dest: '/usr/local/sbin/'
      src: 'postconf_yaml.sh'
      owner: 'root'
      group: 'root'
      mode: '0750'

- name: Existing non-default postfix options are retrieved as a YAML dictionary
  command: /usr/local/sbin/postconf_yaml.sh
  changed_when: False  # only looking
  register: result

- name: Stderr output from script is debugged
  debug:
      msg: '{{ result.stderr }}'
  when: result.stderr | default('',True) | trim | length

- name: Buffer is parsed as a YAML dictionary
  set_fact:
    result: '{{ result.stdout | from_yaml }}'

- name: Buffer contents are validated
  assert:
    that: 'item in result.postfix_configuration'
  with_items:  # These are always/reliable non-default keys
    - 'alias_database'
    - 'alias_maps'
    - 'mail_owner'
