---

- name: Other zones can use Wan zone with masquerading
  firewalld:
      zone: '{{ gateway_wan_zone }}'
      masquerade: True
      permanent: '{{ gateway_settings_permanent }}'
      state: 'enabled'
      immediate: True
  notify: Firewalld reloaded when permanent

- name: Other zones can NOT use Lan zone with masquerading
  firewalld:
      zone: '{{ gateway_lan_zone }}'
      masquerade: False
      permanent: '{{ gateway_settings_permanent }}'
      state: 'disabled'
      immediate: True
  notify: Firewalld reloaded when permanent

- name: External zone is set as the default
  command: >-
      firewall-cmd --set-default-zone=external
